version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "19006:19006"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: truejust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
